RuleOf72Project/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lessons/', include('lessons.urls')),
    path('', include('home.urls')),
    path('forum/', include('forum.urls')),
    path('accounts/', include('allauth.urls')),
    path('purchases/', include('purchases.urls')),
]

forum/urls.py
from django.urls import path
import forum.views


urlpatterns = [
    path('<lesson_id>/', forum.views.show_forum, name="show_forum_route"),
    path('create/<lesson_id>/', forum.views.create_forum,
         name="create_forum_route"),
    path('update/<lesson_id>/<topic_id>/', forum.views.update_forum,
         name="update_forum_route"),
    path('delete/<lesson_id>/<topic_id>/', forum.views.delete_forum,
         name="delete_forum_route"),
    path('<lesson_id>/<topic_id>/', forum.views.show_specific_topic,
         name="specific_topic_route"),
    path('<lesson_id>/<topic_id>/create/comment/',
         forum.views.create_comment,
         name="create_comment_route"),
    path('<lesson_id>/<topic_id>/<comment_id>/update/',
         forum.views.update_comment,
         name="update_comment_route"),
    path('<lesson_id>/<topic_id>/<comment_id>/delete/',
         forum.views.delete_comment,
         name="delete_comment_route"),
]

home/urls.py
from django.urls import path
import home.views


urlpatterns = [
    path('', home.views.home, name="home_route"),
    path('success/', home.views.home),
]

forum/models.py
from django.db import models
from lessons.models import Lesson
from django.contrib.auth.models import User


class Forum_topic(models.Model):
    title = models.CharField(blank=False, max_length=255)
    content = models.TextField(blank=False)
    date_created = models.DateTimeField(auto_now_add=True, blank=True)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE)
    lesson_commented = models.ForeignKey(Lesson, on_delete=models.CASCADE)

    def __str__(self):
        return self.commenter.username + "'s thread"


class Forum_comment(models.Model):
    title = models.CharField(blank=False, max_length=255)
    date_created = models.DateTimeField(auto_now_add=True, blank=True)
    commenter = commenter = models.ForeignKey(User, on_delete=models.CASCADE)
    topic_commented = models.ForeignKey(Forum_topic, on_delete=models.CASCADE)
    content = models.TextField(blank=False)

    def __str__(self):
        return 'Commented by: ' + self.commenter.username

forum/forms.py
from django import forms
from lessons.models import Lesson, Sub_topic
from .models import Forum_comment, Forum_topic
from django.contrib.auth.models import User


class Forum_form(forms.ModelForm):
    class Meta:
        model = Forum_topic
        fields = ('title', 'content')


class Comment_form(forms.ModelForm):
    class Meta:
        model = Forum_comment
        fields = ('title', 'content')


class SearchForm(forms.Form):
    title = forms.CharField(max_length=255, required=False)

forum/views.py
from django.shortcuts import (render, HttpResponse, get_object_or_404,
                              redirect, reverse)
from lessons.forms import Lessons_form, Subtopics_form
from lessons.models import Lesson, Sub_topic
from .forms import Forum_form, Comment_form, SearchForm
from .models import Forum_comment, Forum_topic
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
# Create your views here.


@login_required
def show_forum(request, lesson_id):
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    discussions = Forum_topic.objects.filter(lesson_commented_id=lesson_id)
    if request.GET:
        # always true query:
        queries = ~Q(pk__in=[])
        if 'title' in request.GET and request.GET['title']:
            title = request.GET['title']
            queries = queries & Q(title__icontains=title)
        discussions = discussions.filter(queries)
    search_form = SearchForm(request.GET)
    return render(request, 'forum/forum_topic.template.html', {
        'lesson': lesson_being_viewed,
        'discussions': discussions,
        'search_form': search_form
        })


@login_required
def create_forum(request, lesson_id):
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    if request.method == "POST":
        form = Forum_form(request.POST)
        if form.is_valid():
            forum = form.save(commit=False)
            forum.commenter = request.user
            forum.lesson_commented = lesson_being_viewed
            forum.save()
            messages.success(request,
                             f"""New Forum Topic
                             {form.cleaned_data['title']}
                             has been created""")
            return redirect(reverse('show_forum_route', kwargs={
                                        'lesson_id': lesson_id
                                    }))
        else:
            return render(request, 'forum/create_forum.template.html', {
                'form': form,
                'lesson': lesson_being_viewed
            })
    else:
        form = Forum_form()
        return render(request, 'forum/create_forum.template.html', {
            'form': form,
            'lesson': lesson_being_viewed
        })


@login_required
def update_forum(request, lesson_id, topic_id):
    forum_being_viewed = get_object_or_404(Forum_topic, pk=topic_id)
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    if request.user == forum_being_viewed.commenter:
        if request.method == "POST":
            forum_form = Forum_form(request.POST, instance=forum_being_viewed)
            if forum_form.is_valid():
                forum_form.save()
                return redirect(reverse('show_forum_route', kwargs={
                                            'lesson_id': lesson_id
                                        }))
            else:
                return render(request, 'forum/update_forum.template.html', {
                    "form": forum_form,
                    "discussion": forum_being_viewed,
                    "lesson": lesson_being_viewed
                })
        else:
            forum_form = Forum_form(instance=forum_being_viewed)
            return render(request, 'forum/update_forum.template.html', {
                "form": forum_form,
                "discussion": forum_being_viewed,
                "lesson": lesson_being_viewed
            })
    else:
        return redirect(reverse('show_forum_route', kwargs={
                                            'lesson_id': lesson_id
                                        }))


@login_required
def delete_forum(request, lesson_id, topic_id):
    forum_being_deleted = get_object_or_404(Forum_topic, pk=topic_id)
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    if request.user == forum_being_deleted.commenter:
        if request.method == "POST":
            forum_being_deleted.delete()
            return redirect(reverse('show_forum_route', kwargs={
                                            'lesson_id': lesson_id
                                        }))
        else:
            return render(request, 'forum/delete_forum.template.html', {
                "discussion": forum_being_deleted,
                "lesson": lesson_being_viewed
            })
    else:
        return redirect(reverse('show_forum_route', kwargs={
                                            'lesson_id': lesson_id
                                        }))


@login_required
def show_specific_topic(request, topic_id, lesson_id):
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    topic_being_viewed = get_object_or_404(Forum_topic, pk=topic_id)
    return render(request, 'forum/specific_forum_topic.template.html', {
        'discussion': topic_being_viewed,
        'lesson': lesson_being_viewed,
        })


@login_required
def create_comment(request, lesson_id, topic_id):
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    topic_being_viewed = get_object_or_404(Forum_topic, pk=topic_id)
    if request.method == "POST":
        form = Comment_form(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.commenter = request.user
            comment.topic_commented = topic_being_viewed
            comment.save()
            messages.success(request,
                             f"""New comment
                             {form.cleaned_data['title']}
                             has been created""")
            return redirect(reverse('specific_topic_route', kwargs={
                                        'lesson_id': lesson_id,
                                        'topic_id': topic_id
                                    }))
        else:
            return render(request, 'forum/create_comment.template.html', {
                'form': form,
                'lesson': lesson_being_viewed,
                'topic': topic_being_viewed
            })
    else:
        form = Comment_form()
        return render(request, 'forum/create_comment.template.html', {
            'form': form,
            'lesson': lesson_being_viewed,
            'topic': topic_being_viewed
        })


@login_required
def update_comment(request, lesson_id, topic_id, comment_id):
    forum_being_viewed = get_object_or_404(Forum_topic, pk=topic_id)
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    comment_being_viewed = get_object_or_404(Forum_comment, pk=comment_id)
    if request.user == comment_being_viewed.commenter:
        if request.method == "POST":
            comment_form = Comment_form(request.POST,
                                        instance=comment_being_viewed)
            if comment_form.is_valid():
                comment_form.save()
                return redirect(reverse('specific_topic_route', kwargs={
                                            'lesson_id': lesson_id,
                                            'topic_id': topic_id
                                        }))
            else:
                return render(request, 'forum/update_comment.template.html', {
                    "form": comment_form,
                    "discussion": forum_being_viewed,
                    "lesson": lesson_being_viewed,
                    "comment": comment_being_viewed
                })
        else:
            comment_form = Comment_form(instance=comment_being_viewed)
            return render(request, 'forum/update_comment.template.html', {
                "form": comment_form,
                "discussion": forum_being_viewed,
                "lesson": lesson_being_viewed,
                "comment": comment_being_viewed
            })
    else:
        return redirect(reverse('specific_topic_route', kwargs={
                                            'lesson_id': lesson_id,
                                            'topic_id': topic_id
                                        }))


@login_required
def delete_comment(request, lesson_id, topic_id, comment_id):
    forum_being_viewed = get_object_or_404(Forum_topic, pk=topic_id)
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    comment_being_viewed = get_object_or_404(Forum_comment, pk=comment_id)
    if request.user == comment_being_viewed.commenter:
        if request.method == "POST":
            comment_being_viewed.delete()
            return redirect(reverse('specific_topic_route', kwargs={
                                            'lesson_id': lesson_id,
                                            'topic_id': topic_id
                                        }))
        else:
            return render(request, 'forum/delete_comment.template.html', {
                "discussion": forum_being_viewed,
                "lesson": lesson_being_viewed,
                "comment": comment_being_viewed
            })
    else:
        return redirect(reverse('specific_topic_route', kwargs={
                                            'lesson_id': lesson_id,
                                            'topic_id': topic_id
                                        }))

forum/templates/forum/create_comment.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Create comment for: {{topic.title}}
{% endblock%}
{% block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Comment on: </h1><h3>{{topic.title}}</h3>
    <form method="POST" action="{% url 'create_comment_route' lesson_id=lesson.id topic_id=topic.id %}">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Comment" class="btn create-btn"/>
    </form>
    <a href="{% url 'specific_topic_route' lesson_id=lesson.id topic_id=topic.id %}" class="btn create-btn">No</a>
</div>

{%endblock%}

forum/templates/forum/create_forum.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Create a forum topic
{% endblock%}
{% block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Create a Forum Topic</h1>
    <form method="POST" action="{% url 'create_forum_route' lesson_id=lesson.id %}">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn create-btn"/>
    </form>
    <a href="{% url 'show_forum_route' lesson_id=lesson.id %}" class="btn create-btn">No</a>
</div>
{%endblock%}

forum/templates/forum/delete_comment.template.html
{% extends 'base.template.html' %}
{% block title %}
    Delete comment for: {{comment.title}}
{% endblock%}
{%block content%}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Are you sure you want to delete the comment:</h1><h3> {{comment.title}}?</h3>
    <form method="POST" action="{% url 'delete_comment_route' lesson_id=lesson.id topic_id=discussion.id comment_id=comment.id %}">
        {% csrf_token %}
        <a href="{% url 'specific_topic_route' lesson_id=lesson.id topic_id=discussion.id %}" class="btn create-btn">No</a>
        <input type="submit" class="btn delete-btn" value="Yes">
    <form>
</div>
{%endblock%}

forum/templates/forum/delete_forum.template.html
{% extends 'base.template.html' %}
{% block title %}
    Delete: {{discussion.title}}
{% endblock%}
{%block content%}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Are you sure you want to delete the discussion:</h1><h3>  "{{discussion.title}}"?</h3>
    <form method="POST" action="{% url 'delete_forum_route' lesson_id=lesson.id topic_id=discussion.id %}">
        {% csrf_token %}
        <a href="{% url 'show_forum_route' lesson_id=lesson.id %}" class="btn create-btn">No</a>
        <input type="submit" class="btn delete-btn" value="Yes">
    <form>
</div>
{%endblock%}

forum/templates/forum/forum_topic.template.html
{% extends 'base.template.html' %}
{%load static %}
{% load crispy_forms_tags %}
{% block title %}
    Forum for: {{lesson.topic}}
{% endblock%}
{% block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Welcome to the Forum for:</h1><h3> {{lesson.topic}}</h3>
    <form method="GET">
    {{search_form|crispy}}
    <input type="submit" value="Search" class="account-btn w-100"/>
    </form>
    <button class="create-btn w-100">
        <a href="{% url 'create_forum_route' lesson_id=lesson.id %}">Create a Discussion</a>
    </button>
    <ul>
    {% for discussion in discussions %}
        <div>
            <li>
                <a href="{% url 'specific_topic_route' lesson_id=lesson.id topic_id=discussion.id %}" class="btn forum-link">{{discussion.title}}</a>
                {% if request.user == discussion.commenter %}
                <a href="{% url 'update_forum_route' lesson_id=lesson.id topic_id=discussion.id %}" class="btn create-btn">Edit</a>
                <a href="{% url 'delete_forum_route' lesson_id=lesson.id topic_id=discussion.id %}" class="btn delete-btn">Delete</a> 
                {%endif%}
            </li>
        </div>
    {% endfor %}      
    </ul>
</div>
{%endblock%}

forum/templates/forum/specific_forum_topic.template.html
{% extends 'base.template.html' %}
{% block title %}
    {{lesson.topic}}'s discussion: {{discussion.title}}
{% endblock%}
{% block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1 class="mb-2">{{lesson.topic}}'s discussion:</h1>
    <div class="card lesson-card" style="color:black; text-align:center;">
        <h3> {{discussion.title}}</h3>
        <hr class="my-4">
        {{discussion.content}}
        <hr class="my-4">
        <p style="color:black; text-align:center;"><b>{{discussion.commenter}}</b> commented on {{discussion.date_created}}</p>
    </div>
    <a href="{% url 'create_comment_route' lesson_id=lesson.id topic_id=discussion.id %}" class="btn create-btn w-50">Comment on this discussion!</a>
    <p><h1>Replies:</h1></p>
    {% for r in discussion.forum_comment_set.all %}
    <div class="card lesson-card mt-5 mb-5">
        <h3 style="color:black; text-align:center;" class="mt-2"><b>{{r.title}}</b></h3>
        <hr class="my-4">
        <p style="color:black; text-align:center;">{{r.content}}</p>
        <hr class="my-4">
        <p style="color:black; text-align:center;"><b>{{r.commenter}}</b> commented on {{r.date_created}}</p>
        {% if request.user == r.commenter %}
        <a href="{% url 'update_comment_route' lesson_id=lesson.id topic_id=discussion.id comment_id=r.id %}" class="btn edit-btn">Edit</a>
        <a href="{% url 'delete_comment_route' lesson_id=lesson.id topic_id=discussion.id comment_id=r.id %}" class="btn delete-btn">Delete</a> 
        {%endif%}
    </div>
    {%endfor%}
</div>
{%endblock%}

forum/templates/forum/update_comment.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Update: {{comment.title}}
{% endblock%}
{% block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Update: {{comment.title}}</h1>

    <form method="POST" action="{% url 'update_comment_route' lesson_id=lesson.id topic_id=discussion.id comment_id=comment.id %}">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn create-btn"/>
    </form>
    <a href="{% url 'specific_topic_route' lesson_id=lesson.id topic_id=discussion.id %}" class="btn create-btn">No</a>
</div>
{%endblock%}

forum/templates/forum/update_forum.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Update: {{discussion.title}}
{% endblock%}
{% block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Update:</h1><h3> {{discussion.title}}</h3>

    <form method="POST" action="{% url 'update_forum_route' lesson_id=lesson.id topic_id=discussion.id %}">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn create-btn"/>
    </form>

    <a href="{% url 'show_forum_route' lesson_id=lesson.id %}" class="btn create-btn">No</a>
</div>
{%endblock%}