RuleOf72Project/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lessons/', include('lessons.urls')),
    path('', include('home.urls')),
    path('forum/', include('forum.urls')),
    path('accounts/', include('allauth.urls')),
    path('purchases/', include('purchases.urls')),
]

home/urls.py
from django.urls import path
import home.views


urlpatterns = [
    path('', home.views.home, name="home_route"),
    path('success/', home.views.home),
]

lessons/urls.py
from django.urls import path
import lessons.views


urlpatterns = [
    path('create/', lessons.views.create_lesson,
         name='create_lesson_route'),
    path('update/<lesson_id>/',
         lessons.views.update_lesson,
         name='update_lesson_route'),
    path('lessons/',
         lessons.views.all_lessons,
         name='all_lesson_route'),
    path('delete/<lesson_id>/',
         lessons.views.delete_lesson,
         name='delete_lesson_route'),
    path('lessons/<lesson_id>/',
         lessons.views.specific_lesson,
         name='specific_lesson_route'),
    path('lessons/<lesson_id>/addtopic/',
         lessons.views.add_sub_topic,
         name='add_sub_topic_route'),
    path('lessons/<lesson_id>/updatetopic/<sub_topic_id>/',
         lessons.views.update_sub_topic,
         name='update_sub_topic_route'),
    path('delete/<lesson_id>/topic/<sub_topic_id>/',
         lessons.views.delete_sub_topic,
         name='delete_sub_topic_route'),
    path('created/',
         lessons.views.created_lessons,
         name='created_lesson_route'),
    path('purchased/',
         lessons.views.purchased_lessons,
         name='purchased_lesson_route'),
]

lessons/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


class Lesson(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, blank=True)
    topic = models.CharField(blank=False, max_length=255)
    price = models.PositiveIntegerField(blank=False, default=0)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    introduction = models.TextField(blank=True)
    picture = CloudinaryField()

    def __str__(self):
        return str(self.topic) + ' by: ' + str(self.teacher.username)


class Sub_topic(models.Model):
    title = models.CharField(blank=False, max_length=255)
    video = models.CharField(blank=True, max_length=255)
    content = models.TextField(blank=False)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.title)

lessons/forms.py
from django import forms
from .models import Lesson, Sub_topic
from django.contrib.auth.models import User
from cloudinary.forms import CloudinaryJsFileField


class Lessons_form(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('topic', 'introduction', 'picture', 'price')
    picture = CloudinaryJsFileField()


class Subtopics_form(forms.ModelForm):
    class Meta:
        model = Sub_topic
        fields = ('title', 'video', 'content')


class SearchForm(forms.Form):
    topic = forms.CharField(max_length=255, required=False)

lessons/views.py
from django.shortcuts import (render, HttpResponse, get_object_or_404,
                              redirect, reverse)
from .forms import Lessons_form, Subtopics_form, SearchForm
from .models import Lesson, Sub_topic
from purchases.models import Purchase
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.db.models import Q


@login_required
def all_lessons(request):
    all_lessons = Lesson.objects.all()
    if request.GET:
        queries = ~Q(pk__in=[])
        if 'topic' in request.GET and request.GET['topic']:
            topic = request.GET['topic']
            queries = queries & Q(topic__icontains=topic)
        all_lessons = all_lessons.filter(queries)
    search_form = SearchForm(request.GET)
    return render(request, "lessons/all_lessons.template.html", {
        'all_lessons': all_lessons,
        'search_form': search_form,
    })


@login_required
def create_lesson(request):
    if request.method == "POST":
        form = Lessons_form(request.POST)
        if form.is_valid():
            lesson = form.save(commit=False)
            lesson.teacher = request.user
            lesson.save()
            messages.success(request, f"""New lesson
                             {form.cleaned_data['topic']} has been created""")
            return redirect(reverse(all_lessons))
        else:
            return render(request, 'lessons/create_lessons.template.html', {
                'form': form
            })
    else:
        form = Lessons_form()
        return render(request, 'lessons/create_lessons.template.html', {
            'form': form
        })


@login_required
def update_lesson(request, lesson_id):
    lesson_being_updated = get_object_or_404(Lesson, pk=lesson_id)
    if request.user == lesson_being_updated.teacher:
        if request.method == "POST":
            lesson_form = Lessons_form(request.POST,
                                       instance=lesson_being_updated)
            if lesson_form.is_valid():
                lesson_form.save()
                return redirect(reverse(created_lessons))
            else:
                return render(request,
                              'lessons/update_lessons.template.html',
                              {
                                "form": lesson_form,
                                "lesson": lesson_being_updated
                              })
        else:
            lesson_form = Lessons_form(instance=lesson_being_updated)
            return render(request, 'lessons/update_lessons.template.html', {
                "form": lesson_form,
                "lesson": lesson_being_updated
            })

    else:
        return redirect(reverse(all_lessons))


@login_required
def delete_lesson(request, lesson_id):
    lesson_being_deleted = get_object_or_404(Lesson, pk=lesson_id)
    if request.user == lesson_being_deleted.teacher:
        if request.method == "POST":
            lesson_being_deleted.delete()
            return redirect(reverse(all_lessons))
        else:
            return render(request, 'lessons/delete_lessons.template.html', {
                "lesson": lesson_being_deleted
            })
    else:
        return redirect(reverse(all_lessons))


@login_required
def specific_lesson(request, lesson_id):
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    return render(request, 'lessons/specific_lessons.template.html', {
        'lesson': lesson_being_viewed
    })


@login_required
def add_sub_topic(request, lesson_id):
    form = Subtopics_form(request.POST)
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    if request.user == lesson_being_viewed.teacher:
        if request.method == "POST":
            if form.is_valid():
                subtopic = form.save(commit=False)
                subtopic.lesson = get_object_or_404(Lesson, pk=lesson_id)
                subtopic.save()
                return redirect(reverse('specific_lesson_route',
                                        kwargs={
                                            'lesson_id': lesson_id
                                        }))
            else:
                return render(request, 'lessons/add_sub_topic.template.html', {
                    'form': form,
                    'lesson': lesson_being_viewed
                })
        else:
            form = Subtopics_form()
            return render(request, 'lessons/add_sub_topic.template.html', {
                'form': form,
                'lesson': lesson_being_viewed
            })
    else:
        return redirect(reverse('specific_lesson_route',
                                kwargs={
                                    'lesson_id': lesson_id
                                }))


@login_required
def update_sub_topic(request, lesson_id, sub_topic_id):
    topic_being_updated = get_object_or_404(Sub_topic, pk=sub_topic_id)
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    sub_topic_form = Subtopics_form(request.POST, instance=topic_being_updated)
    if request.user == lesson_being_viewed.teacher:
        if request.method == "POST":
            if sub_topic_form.is_valid():
                sub_topic_form.save()
                return redirect(reverse('specific_lesson_route',
                                        kwargs={
                                            'lesson_id': lesson_id
                                        }))
            else:
                return render(request,
                              'lessons/update_sub_topic.template.html',
                              {
                                "form": sub_topic_form,
                                "lesson": lesson_being_viewed,
                                "sub_topic": topic_being_updated
                              })
        else:
            sub_topic_form = Subtopics_form(instance=topic_being_updated)
            return render(request, 'lessons/update_sub_topic.template.html', {
                "form": sub_topic_form,
                'sub_topic': topic_being_updated,
                "lesson": lesson_being_viewed
            })
    else:
        return redirect(reverse('specific_lesson_route',
                                kwargs={
                                    'lesson_id': lesson_id
                                }))


@login_required
def delete_sub_topic(request, lesson_id, sub_topic_id):
    topic_being_deleted = get_object_or_404(Sub_topic, pk=sub_topic_id)
    lesson_being_viewed = get_object_or_404(Lesson, pk=lesson_id)
    if request.user == lesson_being_viewed.teacher:
        if request.method == "POST":
            topic_being_deleted.delete()
            return redirect(reverse('specific_lesson_route',
                                    kwargs={
                                        'lesson_id': lesson_id
                                    }))
        else:
            return render(request, 'lessons/delete_sub_topic.template.html', {
                "sub_topic": topic_being_deleted,
                "lesson": lesson_being_viewed
            })
    else:
        return redirect(reverse('specific_lesson_route',
                        kwargs={
                            'lesson_id': lesson_id,
                            'sub_topic_id': sub_topic_id
                        }))


@login_required
def created_lessons(request):
    all_lessons = Lesson.objects.filter(teacher=request.user)
    return render(request, "lessons/created_lessons.template.html", {
        'all_lessons': all_lessons
    })


@login_required
def purchased_lessons(request):
    lesson = Purchase.objects.filter(student=request.user)
    return render(request, "lessons/purchased_lessons.template.html", {
        'all_lessons': lesson
    })

lessons/templates/lessons/add_sub_topic.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Add topic for: {{lesson.topic}}
{% endblock%}
{%block content%}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Add a topic to {{lesson.topic}}</h1>

    <form method="POST" action="{% url 'add_sub_topic_route' lesson_id=lesson.id %}">
        {% csrf_token %}
        {{ form|crispy}}
        <input class="btn create-btn" type="submit"/>
    </form>
</div>


{%endblock%}

lessons/templates/lessons/all_lessons.template.html
{% extends 'base.template.html' %} 
{% load crispy_forms_tags %} 
{% load cloudinary %}
{% block title %}
    All Lessons
{% endblock%} 
{% block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
  <h1>Search for a lesson</h1>
  <form method="GET">
    {{search_form|crispy}}
    <input type="submit" value="Search" class="account-btn w-100" />
  </form>
  <button class="create-btn w-100">
    <a href="{% url 'create_lesson_route' %}">Create a lesson</a>
  </button>
{% if all_lessons %}
  {% for each_lesson in all_lessons %}
  <div class="row row-cols-1 row-cols-lg-2 d-flex justify-content-center align-items-center mt-3 mb-3">
    <div class="card lesson-card" style="width: 18rem;">
      {% cloudinary each_lesson.picture class="card-img-top" %}
      <div class="card-body">
        <h5 class="card-title text-center font-weight-bold">
          {{each_lesson.topic}}
        </h5>
        <hr class="my-4"/>
        <div id="accordion_{{each_lesson.id}}">
          <div class="card">
            <div class="card-header" id="intro_{{each_lesson.id}}">
              <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapse_{{each_lesson.id}}" aria-expanded="false" aria-controls="collapse_{{each_lesson.id}}">
                  Introduction
                </button>
              </h5>
            </div>

            <div id="collapse_{{each_lesson.id}}" class="collapse" aria-labelledby="intro_{{each_lesson.id}}" data-parent="#accordion_{{each_lesson.id}}">
              <div class="card-body">
                <p class="card-text text-center">
                <b>About this Lesson:</b> {{each_lesson.introduction}}
                </p>
              </div>
            </div>
          </div>
          <hr class="my-4"/>
          <p class="card-text text-center">Price: ${{each_lesson.price}}</p>
          <hr class="my-4" />
          {% if request.user != each_lesson.teacher %}
          <a href="{% url 'checkout_route' lesson_id=each_lesson.id %}" class="btn purchase-btn">Buy now</a>
          {%endif%}
        </div>
      </div>
    </div>
  </div>
    {% endfor %}
    {%else%}
        <div class="d-flex justify-content-center mt-5"><h3>No results found! Please try again.</h3></div>
    {%endif%}
  {%endblock%}
</div>

lessons/templates/lessons/create_lessons.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}
{% load cloudinary %}
{% load static %}
{% block title %}
    Create a lesson
{% endblock%}
{%block content %}
<div class="container mb-5 mt-5" id="all-lessons-container">
    <h1>Create a Lesson</h1>
    <form method="POST" enctype="multipart/form-data" id="form">
        {%csrf_token%}
        {{form|crispy}}
        <input class="btn create-btn" type="submit"/>
    </form>
</div>

{%endblock%}

{% block js %}
{% cloudinary_includes %}
{% cloudinary_js_config %}
<script>
  function prettydump(obj) {
    ret = ""
    $.each(obj, function(key, value) {
      ret += "<tr><td>" + key + "</td><td>" + value + "</td></tr>";
    });
    return ret;
  }
  $(function () {
    $('#form input[type="file"]')
    .cloudinary_fileupload({
      dropZone: '#form',
      start: function () {
        $('.status_value').text('Starting direct upload...');
      },
      progress: function () {
        $('.status_value').text('Uploading...');
      },
    })
    .on('cloudinarydone', function (e, data) {
        $('.status_value').text('Updating backend...');
        var info = $('<div class="uploaded_info"/>');
        $(info).append($('<div class="data"/>').append(prettydump(data.result)));
        $(info).append($('<div class="image"/>').append(
           $.cloudinary.image(data.result.public_id, {
           format: data.result.format, width: 150, height: 150, crop: "fill"
           })
        ));
        $('.uploaded_info_holder').append(info);
        $('#form  input[type="file"]').parent().parent().remove();
    });
  });
</script>
{% endblock %}

lessons/templates/lessons/created_lessons.template.html
{% extends 'base.template.html' %} 
{% load crispy_forms_tags %} 
{% load cloudinary %}
{% block title %}
    My created lessons
{% endblock%} 
{% block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>My Created Lessons</h1>
  <button class="create-btn w-100">
    <a href="{% url 'create_lesson_route' %}">Create a lesson</a>
  </button>
{% if all_lessons %}
    {% for each_lesson in all_lessons %}
    <div class="row row-cols-1 row-cols-lg-2 d-flex justify-content-center align-items-center mt-3">
        <div class="card lesson-card" style="width: 18rem;">
        {% cloudinary each_lesson.picture class="card-img-top" %}
        <div class="card-body">
            <h5 class="card-title text-center font-weight-bold">
            {{each_lesson.topic}}
            </h5>
            <hr class="my-4"/>
            <div id="accordion_{{each_lesson.id}}">
            <div class="card">
                <div class="card-header" id="intro_{{each_lesson.id}}">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse_{{each_lesson.id}}" aria-expanded="false" aria-controls="collapse_{{each_lesson.id}}">
                    Introduction
                    </button>
                </h5>
                </div>

                <div id="collapse_{{each_lesson.id}}" class="collapse" aria-labelledby="intro_{{each_lesson.id}}" data-parent="#accordion_{{each_lesson.id}}">
                <div class="card-body">
                    <p class="card-text text-center">
                    About this Lesson: {{each_lesson.introduction}}
                    </p>
                </div>
                </div>
            </div>
            <hr class="my-4"/>
            <p class="card-text text-center">Price: ${{each_lesson.price}}</p>
            <hr class="my-4" />
            <a href="{% url 'specific_lesson_route' lesson_id=each_lesson.id %}" class="btn details-btn">Details</a>
            <a href="{% url 'update_lesson_route' lesson_id=each_lesson.id %}" class="btn edit-btn">Update</a>
            <a href="{% url 'delete_lesson_route' lesson_id=each_lesson.id %}" class="btn delete-btn">Delete</a>
            </div>
        </div>
        </div>
    </div>
    {% endfor %}
{%else%}
   <div class="d-flex justify-content-center mt-5"><h3>You have not created any lesson yet. Lets change that!</h3></div>
{%endif%}
{%endblock%}
</div>

lessons/templates/lessons/delete_lessons.template.html
{% extends 'base.template.html' %}
{% block title %}
    Delete lesson: {{lesson.topic}}
{% endblock%}
{%block content%}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Are you sure you want to delete the lesson "{{lesson.topic}}"?</h1>
    <form method="POST">
        {% csrf_token %}
        <a href="{% url 'all_lesson_route' %}" class="btn create-btn">No</a>
        <input type="submit" class="btn delete-btn" value="Yes">
    </form>
</div>
{%endblock%}

lessons/templates/lessons/delete_sub_topic.template.html
{% extends 'base.template.html' %}
{% block title %}
    Delete topic: {{sub_topic.title}}
{% endblock%}
{%block content%}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Are you sure you want to delete the topic "{{sub_topic.title}}"?</h1>
    <form method="POST">
    {% csrf_token %}
        <a href="{% url 'specific_lesson_route' lesson_id=lesson.id %}" class="btn create-btn">No</a>
        <input type="submit" class="btn delete-btn" value="Yes">
    </form>
</div>

{%endblock%}

lessons/templates/lessons/purchased_lessons.template.html
{% extends 'base.template.html' %} 
{% load crispy_forms_tags %}
{% load static %}
{% load cloudinary %}
{% block title %}
    My purchased lessons
{% endblock%} 
{% block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>My Purchased Lessons</h1>
{% if all_lessons %}
    {% for each_lesson in all_lessons %}
    <div class="row row-cols-1 row-cols-lg-2 d-flex justify-content-center align-items-center mt-3">
        <div class="card lesson-card" style="width: 18rem;">
        {% cloudinary each_lesson.lesson_purchased.picture class="card-img-top" %}
        <div class="card-body">
            <h5 class="card-title text-center font-weight-bold">
            {{each_lesson.lesson_purchased.topic}}
            </h5>
            <hr class="my-4" />
            <div id="accordion_{{each_lesson.lesson_purchased.id}}">
            <div class="card">
                <div class="card-header" id="intro_{{each_lesson.lesson_purchased.id}}">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse_{{each_lesson.id}}" aria-expanded="false" aria-controls="collapse_{{each_lesson.lesson_purchased.id}}">
                    Introduction
                    </button>
                </h5>
                </div>

                <div id="collapse_{{each_lesson.lesson_purchased.id}}" class="collapse" aria-labelledby="intro_{{each_lesson.lesson_purchased.id}}" data-parent="#accordion_{{each_lesson.lesson_purchased.id}}">
                <div class="card-body">
                    <p class="card-text text-center">
                    About this Lesson: {{each_lesson.lesson_purchased.introduction}}
                    </p>
                </div>
                </div>
            </div>
            <hr class="my-4" />
            <p class="card-text text-center">Price: ${{each_lesson.lesson_purchased.price}}</p>
            <hr class="my-4" />
            <a href="{% url 'specific_lesson_route' lesson_id=each_lesson.lesson_purchased.id %}" class="btn details-btn">Details</a>
            </div>
        </div>
        </div>
    </div>
    {% endfor %}
{%else%}
   <div class="d-flex justify-content-center mt-5"><h3>You have not purchased any lesson yet. Lets change that!</h3></div><a href="{% url 'all_lesson_route' %}" class="btn create-btn w-100">Lessons</a>
{%endif%} 
{%endblock%}
</div>

lessons/templates/lessons/specific_lessons.template.html
{% extends 'base.template.html' %}
{% block title %}
    {{lesson.topic}}
{% endblock%}
{% block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>{{lesson.topic}}</h1>
    {% if request.user == lesson.teacher %}
    <a class="btn create-btn w-100" href="{% url 'add_sub_topic_route' lesson_id=lesson.id %}">Add a topic</a>
    {%endif%}
    <a class="btn create-btn w-100" href="{% url 'show_forum_route' lesson_id=lesson.id%}">View Discussions</a>
    {% if lesson.sub_topic_set.all %}
        {% for r in lesson.sub_topic_set.all %}
        <div class="row row-cols-1 row-cols-lg-2 d-flex justify-content-center align-items-center mt-3 mb-3">
            <div class="card lesson-card" style="width: auto;">
                <iframe src="{{r.video}}" frameborder="0" allowfullscreen height="auto" width="auto"></iframe>
                <h3 class="card-text text-center mt-2">{{r.title}}</h3>
                <hr class="my-4">
                <p class="card-text text-center mt-2">{{r.content}}</p>
                {% if request.user == r.lesson.teacher %}
                    <a class="btn edit-btn w-50" href="{% url 'update_sub_topic_route' sub_topic_id=r.id lesson_id=lesson.id %}">Edit</a>
                    <a class="btn delete-btn w-50" href="{% url 'delete_sub_topic_route' sub_topic_id=r.id lesson_id=lesson.id %}">Delete</a>
                {%endif%}
            </div>
        </div>
        {%endfor%}
    {%elif request.user == lesson.teacher%}
        <h3 class="d-flex justify-content-center mt-5">There's nothing here. Please add a topic.</h3>
    {%else%}
        <h3 class="d-flex justify-content-center mt-5">The creator has not added in any lessons. Please check back at a later date.</h3>
    {%endif%}
</div>
{%endblock%}

lessons/templates/lessons/update_lessons.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}
{% load cloudinary %}
{% load static %}
{% block title %}
    Update lesson: {{lesson.topic}}
{% endblock%}
{%block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Update: {{lesson.topic}}</h1>
    <form method="POST" enctype="multipart/form-data" id="form">
        {%csrf_token%}
        {{form|crispy}}
        <input class="btn create-btn" type="submit"/>
    </form>
</div>

{%endblock%}

{% block js %}
{% cloudinary_includes %}
{% cloudinary_js_config %}
<script>
  function prettydump(obj) {
    ret = ""
    $.each(obj, function(key, value) {
      ret += "<tr><td>" + key + "</td><td>" + value + "</td></tr>";
    });
    return ret;
  }
  $(function () {
    $('#form input[type="file"]')
    .cloudinary_fileupload({
      dropZone: '#form',
      start: function () {
        $('.status_value').text('Starting direct upload...');
      },
      progress: function () {
        $('.status_value').text('Uploading...');
      },
    })
    .on('cloudinarydone', function (e, data) {
        $('.status_value').text('Updating backend...');
        var info = $('<div class="uploaded_info"/>');
        $(info).append($('<div class="data"/>').append(prettydump(data.result)));
        $(info).append($('<div class="image"/>').append(
           $.cloudinary.image(data.result.public_id, {
           format: data.result.format, width: 150, height: 150, crop: "fill"
           })
        ));
        $('.uploaded_info_holder').append(info);
        $('#form  input[type="file"]').parent().parent().remove();
    });
  });
</script>
{% endblock %}

lessons/templates/lessons/update_sub_topic.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}
{% load cloudinary %}
{% load static %}
{% block title %}
    Update topic: {{sub_topic.title}}
{% endblock%}
{%block content %}
<div class="container mt-5 mb-5" id="all-lessons-container">
    <h1>Edit {{sub_topic.title}}</h1>
    <form method="POST" action="{% url 'update_sub_topic_route' sub_topic_id=sub_topic.id lesson_id=lesson.id %}" enctype="multipart/form-data" id="form">
        {%csrf_token%}
        {{form|crispy}}
        <input class="btn create-btn" type="submit"/>
    </form>
</div>

{%endblock%}

{% block js %}
{% cloudinary_includes %}
{% cloudinary_js_config %}
<script>
  function prettydump(obj) {
    ret = ""
    $.each(obj, function(key, value) {
      ret += "<tr><td>" + key + "</td><td>" + value + "</td></tr>";
    });
    return ret;
  }
  $(function () {
    $('#form input[type="file"]')
    .cloudinary_fileupload({
      dropZone: '#form',
      start: function () {
        $('.status_value').text('Starting direct upload...');
      },
      progress: function () {
        $('.status_value').text('Uploading...');
      },
    })
    .on('cloudinarydone', function (e, data) {
        $('.status_value').text('Updating backend...');
        var info = $('<div class="uploaded_info"/>');
        $(info).append($('<div class="data"/>').append(prettydump(data.result)));
        $(info).append($('<div class="image"/>').append(
           $.cloudinary.image(data.result.public_id, {
           format: data.result.format, width: 150, height: 150, crop: "fill"
           })
        ));
        $('.uploaded_info_holder').append(info);
        $('#form  input[type="file"]').parent().parent().remove();
    });
  });
</script>
{% endblock %}